### ISSUE TITLE
Build errors

### ISSUE THREAD

**Issue by babushyam** [Caiyeon/paird#1]
Hi 
I am getting following build errors while trying to build the source code. I was wondering if you could help in getting this resolved.

.\server.go:68:33: cannot use handlers.Ping() (type "github.com/caiyeon/paird/vendor/github.com/labstack/echo".HandlerFunc) as type "github.com/labstack/echo".HandlerFunc in argument to e.GET
.\server.go:69:38: cannot use handlers.Signup() (type "github.com/caiyeon/paird/vendor/github.com/labstack/echo".HandlerFunc) as type "github.com/labstack/echo".HandlerFunc in argument to e.POST
.\server.go:70:48: cannot use handlers.Interactive() (type "github.com/caiyeon/paird/vendor/github.com/labstack/echo".HandlerFunc) as type "github.com/labstack/echo".HandlerFunc in argument to e.POST
.\server.go:71:46: cannot use handlers.SetWebhook() (type "github.com/caiyeon/paird/vendor/github.com/labstack/echo".HandlerFunc) as type "github.com/labstack/echo".HandlerFunc in argument to e.POST
.\server.go:74:42: cannot use handlers.ListTags() (type "github.com/caiyeon/paird/vendor/github.com/labstack/echo".HandlerFunc) as type "github.com/labstack/echo".HandlerFunc in argument to e.POST
.\server.go:75:44: cannot use handlers.AddMyTags() (type "github.com/caiyeon/paird/vendor/github.com/labstack/echo".HandlerFunc) as type "github.com/labstack/echo".HandlerFunc in argument to e.POST
.\server.go:76:52: cannot use handlers.AddSearchTags() (type "github.com/caiyeon/paird/vendor/github.com/labstack/echo".HandlerFunc) as type "github.com/labstack/echo".HandlerFunc in argument to e.POST
.\server.go:77:50: cannot use handlers.ClearAllTags() (type "github.com/caiyeon/paird/vendor/github.com/labstack/echo".HandlerFunc) as type "github.com/labstack/echo".HandlerFunc in argument to e.POST
.\server.go:78:39: cannot use handlers.SetDiet() (type "github.com/caiyeon/paird/vendor/github.com/labstack/echo".HandlerFunc) as type "github.com/labstack/echo".HandlerFunc in argument to e.POST
.\server.go:79:55: cannot use handlers.SetAvailability() (type "github.com/caiyeon/paird/vendor/github.com/labstack/echo".HandlerFunc) as type "github.com/labstack/echo".HandlerFunc in argument to e.POST
.\server.go:79:55: too many errors

**Comment by Caiyeon** [comment]
Hi there, this project is not maintained and will not be supported in any form. Sorry!
